# site title & your name
title: Sean McKenna
name: Sean McKenna

# information about your site
email: mckennapsean@gmail.com
username: mckennapsean
jobTitle: Ph.D. Candidate

# external resources to load
resources: http://mckennapsean.com/website-resources
analytics: UA-53244240-1

# generates data from markdown & yaml
# stored in variable `site.COLLECTION` from `_COLLECTION/`
collections:
  projects:
    output: true
    permalink: /projects/:path/
  coding: 
    output: false
    permalink: /coding/:path/
  games:
    output: false
    permalink: /games/:path/

# support custom redirects (to/from)
gems:
  - jekyll-redirect-from

# ignore files on building site
exclude:
  - "README.md"
  - "LICENSE"
  - "package.json"
  - "node_modules"
