title: Sean McKenna
name: Sean McKenna
email: mckennapsean@gmail.com
jobTitle: Ph.D. Candidate
gravatar: http://www.gravatar.com/avatar/f029704e495cdad146ef1e046c428d3b.png
github: mckennapsean
otherPlaces: mckennapsean
analytics: ???
resources: http://www.cs.utah.edu/~sean/resources/

exclude: [
  "README.md"
]
collections:
  projectsPath: /projects/:path/
  codingPath: /coding/:path/

projects: [
  "bubble-net",
  "vizsec-design-methods",
  "cybersecurity-dashboard",
  "s-corrplot",
  "design-activity-framework",
  "cybersecurity-redesign",
  "compariseq"
]

coding: [
  "code-examples",
  "ray-tracer",
  "netiquette",
  "wood-shader",
  "set-o-gram"
]

codingData:
  "code-examples":
    tag: "samples of programming languages"
    link: "https://github.com/mckennapsean/code-examples"
    image: "code/codeExamples.png"
    imageAlt: "code examples various programming languages"
  "ray-tracer":
    tag: "ray tracer in C++"
    link: "https://github.com/mckennapsean/ray-tracer"
    image: "code/rayTracer.png"
    imageAlt: "ray tracer final render Utah teapot suicide, titled 'One Fateful Night'"
  "netiquette":
    tag: "netiquette: how to behave online"
    link: "https://github.com/mckennapsean/netiquette"
    image: "code/netiquette.png"
    imageAlt: "core rules of netiquette: how to behave online"
  "wood-shader":
    tag: "shader for modeling finished wood"
    link: "https://github.com/mckennapsean/wood-shader"
    image: "code/woodShader.png"
    imageAlt: "GLSL shader for modeling finished wood, implemented from the original paper by Marschner et al."
  "set-o-gram":
    tag: "set-o-gram: visualization of sets"
    link: "https://github.com/mckennapsean/set-o-gram"
    image: "code/setoGram.png"
    imageAlt: "set-o-gram, reimplemented in Processing from original paper by Freiler et al."
