title: Sean McKenna
name: Sean McKenna
email: mckennapsean@gmail.com
jobTitle: Ph.D. Candidate
gravatar: http://www.gravatar.com/avatar/f029704e495cdad146ef1e046c428d3b.png
github: mckennapsean
otherPlaces: mckennapsean
analytics: ???
resources: https://raw.githubusercontent.com/mckennapsean/website-resources/master/

gems:
  - jekyll-redirect-from

exclude: [
  "README.md",
  "LICENSE",
  "package.json",
  "node_modules"
]
collections:
  projects:
    output: true
    permalink: /projects/:path/
  coding: 
    output: false
    permalink: /coding/:path/
